[app]
project_id = "speedy-victory-336109"

[pubsub]
subscription_name = "cs-issue-sub"
max_messages = 1

[bigquery]
dataset_id = "nap_tickets"
text_embedding_model = "gemini-embedding-001"
summary_model = "gemini-25-flash"

raw_table_name = "raw_data"
raw_data_view = "raw_view"
summary_table_name = "issue_summary"
embedding_table_name = "issue_embedding"
cluster_table_name = "issue_cluster"
faq_table_name = "issue_faq"
task_status_table_name = "task_status"

[clustering]
hdbscan_min_samples = 5

[gcs]
source_bucket = "pwm-lowa"